name: Pull Request

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      minio:
        image: wktk/minio-server
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: T77RlV64b2pQpK71UPuA
          MINIO_SECRET_KEY: atvLX0bUmtEJEEFjIh45RVpJFa45ODfBvJd3GFqS

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
