# Taken from: https://github.com/ryansonshine/ryansonshine/blob/main/.github/workflows/release.yml
name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    services:
      minio:
        image: wktk/minio-server
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: nPRQd3IyCfMBV8HUjmyy
          MINIO_SECRET_KEY: dYcdcLpIzgGSwL23m86hA304PtctxNPpXmgZkTAa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Commit package.json and package-lock.json
        run: |
          HUSKY=0 git add package.json package-lock.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            HUSKY=0 git commit -m "chore(release): update package version [skip ci]"
            git push
          fi
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0